[package]
name = "account-data"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.11"
borsh = "0.9.3"
borsh-derive = "0.9.1"

[lib]
name = "hello_world"
crate-type = ["cdylib", "lib"]
